import rsspubsubframework.*;

/**
 * 
 */

/**
 * An internal Message, mostly generated by timertasks, not for showing on
 * display, with runtime=1
 * 
 * @author Friedemann Zintel
 * 
 */
public class InternalMessage extends Message {

	InternalMessage(Node src, Node dst) {
		super(src, dst, 1);
	}

	/**
	 * Should not be drawn
	 * 
	 * @param g
	 */
	public void drawobj(java.awt.Graphics g) {
	}

}
