package de.zintel.diplom.simulation;


/**
 * 
 */

/**
 * An internal Message, mostly generated by timertasks, not for showing on
 * display, with runtime=1
 * 
 * @author Friedemann Zintel
 * 
 */
public class InternalMessage extends Message {

	/**
	 * @param src source
	 * @param dst destination
	 * @param arrivalTime the arrivale-time in case of discrete simulation
	 */
	public InternalMessage(Node src, Node dst, long arrivalTime) {
		super(src, dst, 1);
		setArrivaltime(arrivalTime);
	}

	/**
	 * Should not be drawn
	 * 
	 * @param g
	 */
	public void drawobj(java.awt.Graphics g) {
	}

}
